// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(PersonsDbContext))]
    [Migration("20251226165023_TIN_Updated")]
    partial class TIN_Updated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("2f8c1d8e-7c6a-4e6a-9f7b-1a2d3b4c5e01"),
                            CountryName = "Paraguay"
                        },
                        new
                        {
                            CountryId = new Guid("9b4e2f7a-6c91-4b55-ae8f-2c3d4e5f6a02"),
                            CountryName = "Argentina"
                        },
                        new
                        {
                            CountryId = new Guid("5a6c7d8e-9f01-4b23-8c4d-3e4f5a6b7c03"),
                            CountryName = "Brasil"
                        },
                        new
                        {
                            CountryId = new Guid("1c2d3e4f-5a6b-4c7d-8e9f-0a1b2c3d4e04"),
                            CountryName = "Uruguay"
                        },
                        new
                        {
                            CountryId = new Guid("7e6f5d4c-3b2a-49f8-8c7d-1e2f3a4b5c05"),
                            CountryName = "Chile"
                        },
                        new
                        {
                            CountryId = new Guid("4f3e2d1c-0b9a-48c7-9d8e-5a6b7c8d9e06"),
                            CountryName = "Bolivia"
                        },
                        new
                        {
                            CountryId = new Guid("8a9b0c1d-2e3f-4a5b-8c7d-6e5f4a3b2c07"),
                            CountryName = "Colombia"
                        },
                        new
                        {
                            CountryId = new Guid("6c5b4a3f-2e1d-49a8-9b0c-7d8e9f1a2b08"),
                            CountryName = "Perú"
                        },
                        new
                        {
                            CountryId = new Guid("0e1f2a3b-4c5d-46a7-8b9c-1d2e3f4a5b09"),
                            CountryName = "México"
                        },
                        new
                        {
                            CountryId = new Guid("3d4c5b6a-7e8f-4a9b-0c1d-2e3f4a5b6c10"),
                            CountryName = "España"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("ReceiveNewsLetters")
                        .HasColumnType("bit");

                    b.Property<string>("TIN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("ABC12345")
                        .HasColumnName("TaxIdentificationNumber");

                    b.HasKey("PersonId");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("3e6bf70a-26f0-4ebd-9714-63276b469894"),
                            Address = "303 Fuller Crossing",
                            CountryId = new Guid("2f8c1d8e-7c6a-4e6a-9f7b-1a2d3b4c5e01"),
                            DateOfBirth = new DateTime(1995, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mrampton0@goo.ne.jp",
                            PersonName = "Marshall",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("e4988995-475d-4079-bd26-047f2d0bcc23"),
                            Address = "022 Browning Drive",
                            CountryId = new Guid("9b4e2f7a-6c91-4b55-ae8f-2c3d4e5f6a02"),
                            DateOfBirth = new DateTime(2003, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sepiscopio1@phoca.cz",
                            PersonName = "Skipp",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("d6ffb398-b0e5-42a4-9282-54e901205ea1"),
                            Address = "5 Farmco Alley",
                            CountryId = new Guid("5a6c7d8e-9f01-4b23-8c4d-3e4f5a6b7c03"),
                            DateOfBirth = new DateTime(1994, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sdarke2@studiopress.com",
                            PersonName = "Seth",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("5c4e391b-26ee-4211-b03c-21ad252bc917"),
                            Address = "482 Tomscot Road",
                            CountryId = new Guid("1c2d3e4f-5a6b-4c7d-8e9f-0a1b2c3d4e04"),
                            DateOfBirth = new DateTime(1998, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sgowthorpe3@vimeo.com",
                            PersonName = "Salome",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("a6113eef-0778-4e2b-b01d-5eeb94732a80"),
                            Address = "57023 Shoshone Street",
                            CountryId = new Guid("7e6f5d4c-3b2a-49f8-8c7d-1e2f3a4b5c05"),
                            DateOfBirth = new DateTime(1996, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nmoxted4@youtu.be",
                            PersonName = "Natalie",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("dd988a25-02ff-47a3-9ba9-45493af19c15"),
                            Address = "42 Birchwood Place",
                            CountryId = new Guid("4f3e2d1c-0b9a-48c7-9d8e-5a6b7c8d9e06"),
                            DateOfBirth = new DateTime(2000, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ryakunkin5@howstuffworks.com",
                            PersonName = "Remy",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("e15343ef-4958-49a4-9acc-77976c41d237"),
                            Address = "448 Lake View Circle",
                            CountryId = new Guid("8a9b0c1d-2e3f-4a5b-8c7d-6e5f4a3b2c07"),
                            DateOfBirth = new DateTime(1995, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cbrownlee6@hao123.com",
                            PersonName = "Carlyle",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("366a9cee-9ce4-48d4-b22b-74b12ed22e18"),
                            Address = "10029 Pine View Parkway",
                            CountryId = new Guid("6c5b4a3f-2e1d-49a8-9b0c-7d8e9f1a2b08"),
                            DateOfBirth = new DateTime(1994, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cpatroni7@wikimedia.org",
                            PersonName = "Cori",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("b9453b43-e788-45ff-9c11-4632abb88b18"),
                            Address = "54417 Utah Trail",
                            CountryId = new Guid("0e1f2a3b-4c5d-46a7-8b9c-1d2e3f4a5b09"),
                            DateOfBirth = new DateTime(1996, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aborwick8@elpais.com",
                            PersonName = "Ario",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("eba86d41-1a50-4a85-aac3-dab9fbc47d9b"),
                            Address = "2 Banding Terrace",
                            CountryId = new Guid("3d4c5b6a-7e8f-4a9b-0c1d-2e3f4a5b6c10"),
                            DateOfBirth = new DateTime(2002, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mschops9@mac.com",
                            PersonName = "Miriam",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("a2d79ddb-3eac-404d-8076-1197bb74b0e6"),
                            Address = "5944 Thompson Crossing",
                            CountryId = new Guid("3d4c5b6a-7e8f-4a9b-0c1d-2e3f4a5b6c10"),
                            DateOfBirth = new DateTime(1997, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tseamera@blogs.com",
                            PersonName = "Torre",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("59624736-47bf-467d-8424-f4ec8894de51"),
                            Address = "99619 Kingsford Place",
                            CountryId = new Guid("0e1f2a3b-4c5d-46a7-8b9c-1d2e3f4a5b09"),
                            DateOfBirth = new DateTime(1992, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hcalcottb@naver.com",
                            PersonName = "Happy",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("bb278e1d-e915-485e-809b-04231d318f1e"),
                            Address = "28 Milwaukee Lane",
                            CountryId = new Guid("6c5b4a3f-2e1d-49a8-9b0c-7d8e9f1a2b08"),
                            DateOfBirth = new DateTime(1994, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nivicc@sakura.ne.jp",
                            PersonName = "Neel",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("6bbcc49e-30fe-4000-838a-610ba544d39c"),
                            Address = "0 Mayer Circle",
                            CountryId = new Guid("8a9b0c1d-2e3f-4a5b-8c7d-6e5f4a3b2c07"),
                            DateOfBirth = new DateTime(1995, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "obeneteaud@wikispaces.com",
                            PersonName = "Octavia",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("ee8b5193-eff7-4d74-9d61-cc3b6e39ca72"),
                            Address = "097 Pankratz Court",
                            CountryId = new Guid("4f3e2d1c-0b9a-48c7-9d8e-5a6b7c8d9e06"),
                            DateOfBirth = new DateTime(2002, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "svineye@purevolume.com",
                            PersonName = "Selia",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("486e35fb-6f32-428e-8fcb-bd3a5fff570c"),
                            Address = "886 Cambridge Center",
                            CountryId = new Guid("7e6f5d4c-3b2a-49f8-8c7d-1e2f3a4b5c05"),
                            DateOfBirth = new DateTime(1997, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sbromagef@dropbox.com",
                            PersonName = "Sheppard",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("90866e2c-5c5b-41b8-985a-174d49c177ca"),
                            Address = "015 Mesta Junction",
                            CountryId = new Guid("1c2d3e4f-5a6b-4c7d-8e9f-0a1b2c3d4e04"),
                            DateOfBirth = new DateTime(2002, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gbollinsg@economist.com",
                            PersonName = "Gert",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("6eca3df1-44e9-44ed-ac87-bb724f9b7475"),
                            Address = "8401 Corben Drive",
                            CountryId = new Guid("5a6c7d8e-9f01-4b23-8c4d-3e4f5a6b7c03"),
                            DateOfBirth = new DateTime(2001, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bbuckmasterh@smugmug.com",
                            PersonName = "Barny",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("18487371-fe21-4a32-a852-b96c42152c7c"),
                            Address = "0 Pleasure Street",
                            CountryId = new Guid("9b4e2f7a-6c91-4b55-ae8f-2c3d4e5f6a02"),
                            DateOfBirth = new DateTime(1990, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "afawksi@webs.com",
                            PersonName = "Adolpho",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("b82e27fb-e6d8-40e6-b884-8de0a27c85cf"),
                            Address = "56 Surrey Alley",
                            CountryId = new Guid("2f8c1d8e-7c6a-4e6a-9f7b-1a2d3b4c5e01"),
                            DateOfBirth = new DateTime(1991, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alomasneyj@icq.com",
                            PersonName = "Annecorinne",
                            ReceiveNewsLetters = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
